/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_learnso_JNITest */

#ifndef _Included_com_example_learnso_JNITest
#define _Included_com_example_learnso_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_learnso_JNITest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_learnso_JNITest_getString
  (JNIEnv *env, jobject){
    return (*env).NewStringUTF("成功调用JNI内容");
    }

#ifdef __cplusplus
}
#endif
#endif
